import {writeFile,readFile,mkdir} from 'node:fs/promises';
import {resolve} from 'node:path';
const root=resolve(import.meta.dirname,'..');
const FEEDS=[['Aktuality z městské části','https://www.praha8.cz/rss/490'],['Doprava','https://www.praha8.cz/rss/73567'],['Kultura a volný čas','https://www.praha8.cz/rss/97443'],['Sociální oblast a zdravotnictví','https://www.praha8.cz/rss/75652'],['Sport','https://www.praha8.cz/rss/494'],['Školství','https://www.praha8.cz/rss/67304'],['Životní prostředí','https://www.praha8.cz/rss/79261'],['Informace z úřadu','https://www.praha8.cz/rss/67326']];
const clean=s=>String(s||'').replace(/<!\[CDATA\[|\]\]>/g,'').replace(/<[^>]+>/g,' ').replace(/&nbsp;|&#160;/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/\s+/g,' ').trim();
const tag=(xml,n)=>{const m=xml.match(new RegExp(`<${n}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${n}>`,'i'));return m?clean(m[1]):''};
const parseDate=s=>{const d=new Date(s);return Number.isNaN(d.valueOf())?'':d.toISOString().slice(0,10)};
const all=[],failures=[];for(const [channel,url] of FEEDS){try{const r=await fetch(url,{headers:{'user-agent':'Praha8Prehledy/2.10.2 (+public-data-indexer)'}});if(!r.ok)throw new Error(`HTTP ${r.status}`);const xml=await r.text();const items=[...xml.matchAll(/<item\b[^>]*>([\s\S]*?)<\/item>/gi)].map(m=>m[1]).map(x=>({title:tag(x,'title'),url:tag(x,'link'),date:parseDate(tag(x,'pubDate')||tag(x,'date')),description:tag(x,'description'),channel})).filter(x=>x.title&&x.url);all.push(...items);console.log(`   ${channel}: ${items.length}`)}catch(e){failures.push(channel);console.log(`   ⚠️ ${channel}: ${String(e.message||e)}`)}}
const cutoff=new Date();cutoff.setHours(0,0,0,0);cutoff.setDate(cutoff.getDate()-6);const cutoffDate=cutoff.toISOString().slice(0,10);const items=[...new Map(all.map(x=>[x.url,x])).values()].filter(x=>x.date&&x.date>=cutoffDate).sort((a,b)=>(b.date||'').localeCompare(a.date||'')||(b.title||'').localeCompare(a.title||'','cs'));await mkdir(resolve(root,'data'),{recursive:true});await writeFile(resolve(root,'data/novinky.json'),JSON.stringify(items,null,2));let st={};try{st=JSON.parse(await readFile(resolve(root,'data/source-status.json'),'utf8'))}catch{};st.news={status:items.length?'data načtena':'čeká na naplnění',count:items.length,updated:new Date().toISOString(),mode:items.length?'aktualizováno':'nenačteno',feeds:FEEDS.length,failedFeeds:failures.length};await writeFile(resolve(root,'data/source-status.json'),JSON.stringify(st,null,2));console.log(`✅ Novinky: načteno ${items.length} unikátních položek za posledních 7 dní z ${FEEDS.length-failures.length}/${FEEDS.length} RSS kanálů.`);
